services:
  mis-server:
    build: https://github.com/mis-py/mis-server.git
    image: mis-server:v2.2.0
    container_name: mis-server
    networks:
      - default
      - mis-net
    environment:
      - MAX_WORKERS=1
    env_file: 
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    profiles: ['production']

  mis-web-ui:
    build: https://github.com/mis-py/mis-web-ui.git
    image: mis-web-ui
    container_name: mis-web-ui
    env_file: 
      - .env
    networks:
      - default
      - mis-net
    restart: unless-stopped
    profiles: ['production']

  rabbitmq:
    image: rabbitmq:3.11.13-alpine
    container_name: mis-rabbitmq
    networks:
      - default
      - mis-net
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 5
    profiles: ['production']

  redis:
    image: redis:7.0.10-alpine
    container_name: mis-redis
    networks:
      - default
      - mis-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ['production']

  postgres:
    image: postgres:15.2-alpine
    container_name: mis-postgres
    hostname: mis-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - default
      - mis-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ['production']

  mongodb:
    image: mongo:4.4.18
    restart: unless-stopped
    container_name: mis-mongodb
    env_file:
      - .env
    volumes:
      - ./mongodb:/data/db
    networks:
      - default
      - mis-net
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ['production']

  dev_mongodb:
    extends:
      service: mongodb
    ports:
    - "27017:27017"
    profiles: ['dev']
  
  dev_postgres:
    extends:
      service: postgres
    ports:
    - "5432:5432"
    profiles: ['dev']
  
  dev_redis:
    extends:
      service: redis
    ports:
    - "6379:6379"
    profiles: ['dev']

  dev_rabbitmq:
    extends:
      service: rabbitmq
    ports: 
    - "5672:5672"
    profiles: ['dev']

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file: 
      - .env
    volumes:
      - ./pg_admin/data:/var/lib/pgadmin
    networks:
      - default
      - mis-net
    ports: 
      - "8080:80"
    depends_on:
      - dev_postgres
    restart: unless-stopped
    profiles: ['dev']

networks:
  default:
    internal: true
  mis-net:
    internal: false
